version: '3.8'

services:
  vgg_hist_fe:
    build: .
    ports:
      - 78:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
